name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify directories
        run: |
          pwd
          ls
          ls app
          ls app/backend
          ls app/frontend

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Image
        working-directory: app/backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest .

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

      - name: Build Frontend Image
        working-directory: app/frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest .

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest
            cd ~/devops-capstone-todo-app
            docker compose down
            docker compose up -d
