name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ================= BACKEND =================
      - name: Build Backend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest \
            ./app/backend

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

      # ================= FRONTEND =================
      - name: Build Frontend Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest \
            ./app/frontend

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest

      # ================= DEPLOY =================
      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest
            cd ~/devops-capstone-todo-app
            docker compose down
            docker compose up -d
