name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Login to DockerHub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Build Backend Image
    - name: Build Backend Image
      run: |
        docker buildx build --load \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest \
          ./app/backend

    # 4. Push Backend Image
    - name: Push Backend Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

    # 5. Build Frontend Image
    - name: Build Frontend Image
      run: |
        docker buildx build --load \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest \
          ./app/frontend

    # 6. Push Frontend Image
    - name: Push Frontend Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest

    # 7. Deploy on EC2 Server
    - name: Deploy to EC2 Instance
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest
          cd ~/devops-capstone-todo-app
          sudo docker compose down
          sudo docker compose up -d --build
